### ISSUE TITLE
loop name highlighted

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#10]
For some reason, the name of this loop is highlighted.  But I don't think it should be.
![screen shot 2016-05-11 at 4 24 19 pm](https://cloud.githubusercontent.com/assets/4418497/15195310/45d332e8-1795-11e6-8b6e-7a1782e57fbd.png)

**Comment by 315234** [comment]
This is intentional, it is currently identified as `entity.name.tag.do-loop-label.fortran`. These are also included in the symbol list so that you can use "Go To Definition" on `ADLOOP` to jump to the start of the loop.
