### ISSUE TITLE
About Fortran Build System on Windows

### ISSUE THREAD

**Issue by lch** [Nevensky/SublimeFortran#12]
Thanks for providing such a great Sublime Text plugin. However there seems to be a little problem. When I'm using this plugin on Windows and press `Ctrl+B` , I found it put out an error like:

> gfortran <Source Code Path> Invalid Argument

I've checked the command line that the build system use. The File Name is quoted by apostrophe. So this lead to the gfortran can't recognize. The apostrophe is quite common under Linux, bash treat it as string, but there might be a little different under Windows cmd. I'm using latest TDM-GCC, and get this problem (I have not checked other MinGW distribution). After I modified the build system file, and delete the quoted apostrophe, it works well. 

So I think it will be better to submit an issue to report this problem. I hope it can be fixed in the next version if it can be fixed. Also I think it will be useful to those have same problem.

**Comment by 315234** [comment]
Thanks for your report. Please could you post your modified build system?

**Comment by lch** [comment]
Here is it.

```
{
    "shell_cmd": "gfortran ${file} -o ${file_path}/${file_base_name}",
    "file_regex": "^(?xi:( ^[/] [^:]* ) : (\\d+) : (\\d+) :)",
    "working_dir": "${file_path}",
    "selector": "source.modern-fortran, source.fixedform-fortran",
    "syntax": "GFortranBuild.sublime-syntax",

    "variants":
    [
        {
            "name": "Run",
            "shell_cmd": "gfortran ${file} -o ${file_path}/${file_base_name} && ${file_path}/${file_base_name}"
        }
    ]
}
```

I just delete the apostrophe of the `${file}` in `shell_cmd`.

**Comment by 315234** [comment]
Sorry for the delay. Unfortunately this will break the build system if the filename contains any spaces. I'm not very familiar with Windows development. Does it perhaps work if you replace the single quotes with escaped double quotes?

`"shell_cmd": "gfortran \"${file}\" -o \"${file_path}/${file_base_name}\"",`

**Comment by klonuo** [comment]
IMHO `shell_cmd` is not essential in this case. You could have used simply `cmd` and supply arguments as array (like you do when using `Popen`) so Python would take care of empty spaces, etc... If shell is necessary, you can use `"shell": true` property

Also you can target platforms in sublime build systems: http://docs.sublimetext.info/en/latest/reference/build_systems/configuration.html#platform-specific-options
