### ISSUE TITLE
Fortran Fixed Format Extended Setting

### ISSUE THREAD

**Issue by kenodegard** [Nevensky/SublimeFortran#13]
Any chance to add a settings parameter that controls the fixed format's line width?

**Comment by 315234** [comment]
Can you explain what you mean exactly?

**Comment by kenodegard** [comment]
Fortran has a compile time flag (quoted from https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gfortran/Fortran-Dialect-Options.html):

> **-ffixed-line-length-_n_**
> 
> Set column after which characters are ignored in typical fixed-form lines in the source file, and through which spaces are assumed (as if padded to that length) after the ends of short fixed-form lines.
> 
> Popular values for **_n_** include 72 (the standard and the default), 80 (card image), and 132 (corresponds to “extended-source” options in some popular compilers). **_n_** may be 'none', meaning that the entire line is meaningful and that continued character constants never have implicit spaces appended to them to fill out the line. **-ffixed-line-length-_0_** means the same thing as **-ffixed-line-length-_none_**.

So it would be great if there could be a settings parameter in **Preferences: Settings - User** that would decide the width for the syntax. This would need a small change in the grammar (https://github.com/315234/SublimeFortran/blob/master/grammars/FortranFixedForm.sublime-syntax#L25) and then the ruler (https://github.com/315234/SublimeFortran/blob/master/settings/FortranFixedForm.sublime-settings#L2).

My research so far has not turned up anything related to how to make a syntax customizable via the **Preferences** so this may simply be impossible with the current Sublime framework.

**Comment by 315234** [comment]
Ruler settings can be overwritten by placing a file called `FortranFixedForm.sublime-settings` in your `Packages/User/` containing something like the following:

```
{
    "rulers": []
}
```

As far as I know, there is no way to have settings for a syntax file. If people are finding it annoying I might just have to disable the line-too-long warning color.

**Comment by 315234** [comment]
I've disabled coloring illegal line lengths, since it is not configurable. The per-syntax settings should handle the rest.
