### ISSUE TITLE
Add highlighting to IF blocks

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#14]
To be consistent with DO loop block highlighting, it would be nice to also have IF blocks highlighted.  Thanks!

![screen shot 2016-06-21 at 1 09 12 pm](https://cloud.githubusercontent.com/assets/4418497/16239233/f6651374-37b1-11e6-9c83-efb691a09a3e.png)

**Comment by rmcdermo** [comment]
Works great.  Thanks!

**Comment by rmcdermo** [comment]
Actually, looks like it does not catch ENDIF label.  Sorry for the hassle.  Thanks.
![screen shot 2016-06-21 at 3 58 49 pm](https://cloud.githubusercontent.com/assets/4418497/16244329/6b281708-37c9-11e6-903c-f8690ce801f5.png)

**Comment by 315234** [comment]
Better?

**Comment by rmcdermo** [comment]
Yep.  Thanks!

**Comment by rmcdermo** [comment]
Don't hate me.  When you get time, ELSE and ELSEIF probably need it too:
![screen shot 2016-06-21 at 4 36 30 pm](https://cloud.githubusercontent.com/assets/4418497/16245363/776ffc2e-37ce-11e6-830e-d0509fe75238.png)

**Comment by 315234** [comment]
Third time's the charm?

**Comment by rmcdermo** [comment]
ELSE and ELSEIF are working.  Thanks.  Hopefully, last one: SELECT CASE and subsequent CASE statements (END SELECT seems to be highlighted).
![screen shot 2016-06-22 at 8 23 40 am](https://cloud.githubusercontent.com/assets/4418497/16266514/49096a84-3853-11e6-9497-a1c7686e30da.png)

**Comment by rmcdermo** [comment]
SELECT CASE labels are correctly highlighted if no space is put between "CASE" and argument ( ), as above.  But if a space is present, block highlighting occurs.  The example below shows what works and what doesn't.  Thanks.

![screen shot 2016-06-30 at 8 25 03 am](https://cloud.githubusercontent.com/assets/4418497/16488058/7a024c74-3e9c-11e6-9352-b9a09906bf78.png)

**Comment by 315234** [comment]
Sorry, fixed in v1.0.15.

Just out of interest, are you using Package Control or are you manually pulling from the git repo? If it's the latter I don't have to issue a new release until you check that the fix works.

**Comment by rmcdermo** [comment]
I just been downloading and installing your Releases.  But I have the repo
cloned, so if you can point me to how to build the "package" I'm happy to
try that.

**Comment by rmcdermo** [comment]
Is it as simple as just copying the repo into a directory called, say,
"SublimeFortran-1.0.15"?

**Comment by rmcdermo** [comment]
SublimeFortran-1.0.15 looks good.  Thanks!

**Comment by 315234** [comment]
I've added some installation instructions to the [Readme](https://github.com/315234/SublimeFortran/blob/master/README.md). Don't feel you need to change your workflow on account of this though.

**Comment by rmcdermo** [comment]
Got it.  Thanks!

**Comment by rmcdermo** [comment]
Not that I like this bit of coding, but the over-zealous highlighting seems to include the following:

![screen shot 2016-06-30 at 11 21 54 am](https://cloud.githubusercontent.com/assets/4418497/16493858/18e3b6a8-3eb5-11e6-91c1-bbfb39cb1ecc.png)

**Comment by rmcdermo** [comment]
And I guess the "DO"s in the top line should be highlighted, too.
