### ISSUE TITLE
Do not highlight numbers that are part of variable names

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#17]
Not a big deal, but as things get refined, any numerals used as part of a variable name should probably not be highlighted.  For example, see "STATE1" below.

![screen shot 2016-06-30 at 9 32 27 am](https://cloud.githubusercontent.com/assets/4418497/16490022/f5d83eae-3ea5-11e6-99f6-275daf52b234.png)

**Comment by rmcdermo** [comment]
Looks like might also be tied to Issue #4.  When an underscore follows the numeral that text gets highlight ed.  In this case, it should not.

![screen shot 2016-06-30 at 9 43 28 am](https://cloud.githubusercontent.com/assets/4418497/16490429/95d94c6c-3ea7-11e6-8e51-61065496792e.png)

**Comment by 315234** [comment]
Fixed in latest release

**Comment by rmcdermo** [comment]
Works great.  Thanks!
