### ISSUE TITLE
Comment on Subroutine line

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#3]
In the attached screen shot if a comment is placed on the same line as Subroutine command the highlighting is disabled. (Not that I am advocating for putting comments here, but one of our developers had left this around.) If the comment is moved, the highlighting works fine.

![screen shot 2016-02-25 at 10 36 10 am](https://cloud.githubusercontent.com/assets/4418497/13324468/e68b3ba2-dbab-11e5-8b67-1110662ab620.png)

**Comment by 315234** [comment]
Fixed in v1.0.5

**Comment by rmcdermo** [comment]
Awesome.  Works great.  Thanks.
