### ISSUE TITLE
Disabling tabs as an illegal character

### ISSUE THREAD

**Issue by joezuntz** [Nevensky/SublimeFortran#31]
Although tabs are nominally an illegal character in Fortran not even gfortran warns about this any more.  

Many people have substantial legacy code that uses tabs it's annoying to have a mass of bright pink highlighting at the start of every line.  Is there a way to disable the tab as an illegal character?

**Comment by manfredo89** [comment]
Deleting 

```
    # tabs are illegal
    - match: \t
      scope: invalid.illegal.tab.fortran

```
from the FortranModern.sublime-syntax fix this.

**Comment by 315234** [comment]
If someone makes a pull request for this I will accept it.

**Comment by manfredo89** [comment]
I made a pr
