### ISSUE TITLE
select_real_kind float extensions not highlighted

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#4]
One more for today...  In the attached screenshot you can see that when we create a specific real kind and add this extension to a float the "underscore" and "kind" are not highlighted.  In the image the floats are blue and the extension is black.

![screen shot 2016-02-25 at 4 39 23 pm](https://cloud.githubusercontent.com/assets/4418497/13335399/f2815fc6-dbde-11e5-8453-f745e0689424.png)

**Comment by 315234** [comment]
Fixed in v1.0.6. Keep 'em coming :+1:

**Comment by rmcdermo** [comment]
Works great.  Thanks!
