### ISSUE TITLE
Highlighting Intrinsic functions without ()

### ISSUE THREAD

**Issue by tyleracorn** [Nevensky/SublimeFortran#7]
Hi! First off, thanks for putting this together! This is quite a bit better then the other fortran syntax option in syblime3 and I'm glad I recently found this. One thing I was wondering though, would it be simple to change the syntax so that it finds intrinsic function names that don't have the associated () with them? for instance: find "int " as well as "int()"? This would be helpful in keeping us from using variable names that are also intrinsic function names. 
Cheers,

**Comment by 315234** [comment]
I agree that we shouldn't be using intrinsic functions as identifiers, but unfortunately lots of people do it anyway, so I think only matching them as intrinsics when there is a parenthesis or the `call` keyword is a sensible approach for now.
